import * as stylex from "@stylexjs/stylex";

const enter = stylex.keyframes({
  from: { opacity: 0, transform: "translateY(6px)" },
  to: { opacity: 1, transform: "translateY(0)" },
});

export const styles = stylex.create({
  reveal: {
    animationName: {
      default: "none",
      "@media (prefers-reduced-motion: no-preference)": enter,
    },
    animationDuration: "900ms",
    animationDelay: "var(--reveal-delay, 0ms)",
    animationTimingFunction: "cubic-bezier(0.22, 1, 0.36, 1)",
    animationFillMode: "backwards",
  },
  page: {
    maxWidth: "43rem",
    marginInline: "auto",
    paddingInline: { default: "2rem", "@media (max-width: 480px)": "1.5rem" },
    paddingTop: { default: "6rem", "@media (max-width: 600px)": "3rem" },
    paddingBottom: "2.5rem",
  },
  masthead: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: "1rem",
    marginBottom: { default: "4rem", "@media (max-width: 600px)": "3rem" },
  },
  logoLink: {
    display: "inline-flex",
    textDecoration: "none",
  },
  themeSwitch: {
    display: "flex",
    gap: "0.125rem",
    minWidth: 0,
    margin: 0,
    padding: "0.25rem",
    borderWidth: 0,
    borderRadius: "2rem",
    backgroundColor: "var(--project-fill)",
  },
  themeOption: {
    position: "relative",
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    minWidth: "2.25rem",
    minHeight: "2.25rem",
    paddingInline: "0.625rem",
    borderRadius: "2rem",
    fontSize: "0.75rem",
    color: "var(--theme-option-ink, var(--muted))",
    backgroundColor: "var(--theme-option-fill, transparent)",
    cursor: "pointer",
  },
  themeInput: {
    position: "absolute",
    width: 1,
    height: 1,
    padding: 0,
    margin: -1,
    overflow: "hidden",
    clipPath: "inset(50%)",
    whiteSpace: "nowrap",
  },
  themeIcon: {
    width: "1.125rem",
    height: "1.125rem",
    flexShrink: 0,
  },
  mark: {
    width: "3rem",
    height: "3rem",
    color: "var(--accent-ink)",
    flexShrink: 0,
  },

  main: {
    display: "grid",
    gap: "var(--section-space)",
  },
  intro: {
    display: "grid",
    gap: "1.5rem",
  },
  heroHeading: {
    display: "grid",
    gap: "0.875rem",
  },
  greeting: {
    fontFamily: "var(--font-serif)",
    fontSize: "1.5rem",
    color: "var(--muted)",
  },
  headline: {
    fontFamily: "var(--font-serif)",
    fontSize: "clamp(2.625rem, 6.5vw, 3.625rem)",
    fontWeight: 400,
    letterSpacing: "-0.025em",
    lineHeight: 1.08,
    textWrap: "balance",
  },
  emphasis: {
    color: "var(--accent-ink)",
  },
  bio: {
    maxWidth: "35rem",
    color: "var(--muted)",
    fontSize: "1.0625rem",
    lineHeight: 1.75,
  },
  about: {
    display: "grid",
    gap: "1.25rem",
    color: "var(--muted)",
    fontSize: "0.9375rem",
    lineHeight: 1.8,
  },
  proseEmphasis: {
    color: "var(--ink)",
    fontWeight: 500,
  },
  introAction: {
    justifySelf: "start",
    fontSize: "0.875rem",
  },
  contactLink: {
    display: "inline-flex",
    alignItems: "center",
    gap: "0.5rem",
    transform: {
      default: "translateY(0)",
      ":hover": "translateY(-1px)",
      ":focus-visible": "translateY(-1px)",
    },
    transitionProperty: {
      default: "none",
      "@media (prefers-reduced-motion: no-preference)": "color, text-decoration-color, transform",
    },
    transitionDuration: "180ms",
  },
  contactButton: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    gap: "0.75rem",
    minHeight: "2.875rem",
    padding: "0.75rem 1.125rem",
    borderRadius: "0.5rem",
    backgroundColor: {
      default: "var(--button-fill)",
      ":hover": "var(--button-hover)",
    },
    color: { default: "var(--button-ink)", ":hover": "var(--button-ink)" },
    fontWeight: 500,
    textDecoration: "none",
    transitionProperty: {
      default: "none",
      "@media (prefers-reduced-motion: no-preference)": "background-color, transform",
    },
    transitionDuration: "240ms",
    transform: { default: "translateY(0)", ":hover": "translateY(-2px)" },
  },
  linkIcon: {
    width: "1rem",
    height: "1rem",
    flexShrink: 0,
  },
  arrow: {
    color: "var(--accent-ink)",
  },
  section: {
    borderTopWidth: 0.5,
    borderTopStyle: "solid",
    borderTopColor: "var(--rule)",
    marginInline: "calc(-1 * var(--section-bleed))",
    paddingInline: "var(--section-bleed)",
    paddingTop: "var(--section-space)",
  },
  sectionTitle: {
    fontFamily: "var(--font-mono)",
    color: "var(--muted)",
    fontSize: "0.75rem",
    fontWeight: 400,
    letterSpacing: "0.025em",
    marginBottom: "1.75rem",
  },
  trustedSection: {
    paddingTop: "calc(var(--section-space) / 2)",
    marginBottom: "calc(var(--section-space) / -2)",
  },
  trusted: {
    display: "grid",
    gridTemplateColumns: "1fr 0.7fr 1.4fr",
    alignItems: "center",
    gap: "1.5rem",
    maxWidth: "27rem",
    width: "100%",
    listStyleType: "none",
    padding: 0,
    marginBlock: 0,
    marginInline: "auto",
  },
  trustedLink: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    minHeight: "2.75rem",
  },
  trustedLogo: {
    display: "block",
    width: "100%",
    height: "2rem",
    objectFit: "contain",
    objectPosition: "center",
    opacity: 0.8,
    filter: "var(--logo-filter)",
  },
  tldrawLogo: { maxWidth: "6rem" },
  lwLogo: { maxWidth: "2.6875rem" },
  porscheLogo: { maxWidth: "9rem" },
  projects: {
    display: "grid",
    gap: "0.75rem",
  },
  project: {
    backgroundColor: "var(--project-fill)",
    borderRadius: "0.625rem",
    padding: "1.25rem",
  },
  projectTitle: {
    fontSize: "1rem",
    fontWeight: 500,
    lineHeight: 1.5,
    marginBottom: "0.375rem",
  },
  projectHeading: {
    display: "flex",
    flexWrap: "wrap",
    alignItems: "baseline",
    columnGap: "0.75rem",
  },
  note: {
    fontFamily: "var(--font-mono)",
    fontSize: "0.6875rem",
    color: "var(--muted)",
  },
  description: {
    color: "var(--muted)",
    fontSize: "0.9375rem",
    lineHeight: 1.7,
  },
  experience: {
    display: "grid",
    gap: "2rem",
  },
  experienceRow: {
    display: "grid",
    gridTemplateColumns: { default: "9rem 1fr", "@media (max-width: 600px)": "1fr" },
    columnGap: "1.25rem",
    rowGap: "0.25rem",
    fontSize: "0.9375rem",
  },
  experienceLabel: {
    color: "var(--muted)",
    fontSize: "0.8125rem",
    paddingTop: "0.125rem",
  },
  experienceDetail: {
    color: "var(--muted)",
    fontSize: "0.875rem",
    marginTop: "0.25rem",
  },
  role: {
    fontSize: "0.9375rem",
    fontWeight: 500,
  },
  experienceDescription: {
    color: "var(--muted)",
    fontSize: "0.875rem",
    marginTop: "0.625rem",
  },
  contactSection: {
    marginTop: "calc(var(--contact-space) - var(--section-space))",
    paddingTop: "var(--contact-space)",
    paddingBottom: "calc(var(--contact-space) - var(--section-space))",
  },
  connectText: {
    fontFamily: "var(--font-serif)",
    fontWeight: 400,
    fontSize: "2rem",
    lineHeight: 1.25,
    marginBottom: "1.25rem",
  },
  links: {
    display: "flex",
    flexWrap: "wrap",
    columnGap: "1.5rem",
    rowGap: "0.75rem",
    fontSize: "0.875rem",
  },
  footer: {
    marginTop: "var(--section-space)",
    paddingTop: "var(--section-space)",
    display: "flex",
    flexWrap: "wrap",
    justifyContent: "space-between",
    gap: "0.5rem",
    fontFamily: "var(--font-mono)",
    fontSize: "0.6875rem",
    color: "var(--muted)",
  },
  footerLocation: {
    marginInlineStart: "auto",
    textAlign: "end",
  },
  skip: {
    position: "absolute",
    top: "1rem",
    left: "1rem",
    padding: "0.5rem 1rem",
    backgroundColor: "var(--paper)",
    transform: { default: "translateY(-200%)", ":focus": "translateY(0)" },
  },
});
